repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        name: black
        exclude: 'interplot_minimal.py'
